adding elb-healthcheck in health script

diff --git a/templates/common/sherlockdeploy-health-script b/templates/common/sherlockdeploy-health-script
--- a/templates/common/sherlockdeploy-health-script
+++ b/templates/common/sherlockdeploy-health-script
@@ -2,13 +2,14 @@
 
 HOST_NAME=`hostname`
 STATUS=`curl -I "http://$HOST_NAME:25280/sherlock/intent?q=samsung" | grep "HTTP" | awk '{print $2}'`
-
-VERSION_TO_DEPLOY="<%= @packageVersion %>"
+ELB_HEALTHCHECK_API_STATUS=`curl -s -I "http://$HOST_NAME:25280/elb-healthcheck" | grep "HTTP" | awk '{print $2}'`
+#VERSION_TO_DEPLOY="<%= @packageVersion %>"
 CURRENT_ROTATION_STATUS="<%= @currentRotationStatus %>"
 
-NEW_VERSION=`dpkg -l | grep fk-w3-sherlock | awk '{print $3}'`
+#NEW_VERSION=`dpkg -l | grep fk-w3-sherlock | awk '{print $3}'`
 NEW_ROTATION_STATUS="`fk-w3-sherlock-admin status`"
 SOLR_API="http://$HOST_NAME:25280/solr/admin/cores?action=STATUS&wt=json"
+
 CORE_INIT_FAILURES=`curl -H "Accept: application/json" "$SOLR_API" | grep -Po '("initFailures":{})'`
 CORE_SUCCESS_CRITERIA="\"initFailures\":{}"
 echo "====================================================="
@@ -25,15 +26,27 @@ else
     exit 2
 fi
 
-if [ "$VERSION_TO_DEPLOY" = "$NEW_VERSION" ]
+if [ $ELB_HEALTHCHECK_API_STATUS -eq 200 ]
 then
-    echo "===package version check successful===="
-    echo "package version = $VERSION_TO_DEPLOY"
+    echo "========curl elb health check command successful========"
+    echo "status = $STATUS"
 else
-    echo "=====package version check failed======="
-    echo "Version_to_deploy=$VERSION_TO_DEPLOY   New_version=$NEW_VERSION"
+    echo "===========curl elb health check command failed=========="
+    echo "status = $STATUS"
     exit 2
 fi
+
+
+#if [ "$VERSION_TO_DEPLOY" = "$NEW_VERSION" ]
+#then
+#    echo "===package version check successful===="
+#    echo "package version = $VERSION_TO_DEPLOY"
+#else
+#    echo "=====package version check failed======="
+#    echo "Version_to_deploy=$VERSION_TO_DEPLOY   New_version=$NEW_VERSION"
+#    exit 2
+#fi
+
 
 if [ "$CURRENT_ROTATION_STATUS" = "$NEW_ROTATION_STATUS" ]
 then
